# Konfiguracja komendy /kod
command:
  CodeCommand:
    name: "kod"
    aliases: "code"

# separator do czasu
timeDelimiter: ", "

# czy mają być wyświetlane skrócone formy czasu
# minut -> min itd.
shortFormTime: false

# ile razy gracz z rzędu może przepisać kod
codeInRow: 2

# czas (w sekundach), co jaki ma być następny kod
codeDelayTime: 20

# czas (w sekundach), po jakim kod wygasa
codeExpiredTime: 60

# spośród jakich znaków mają być losowane kody
charList: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()<>?|:{}+_=-][;.,\""

# długość kodu
codeLength: 30

# awardType — typ nagrody, jaką otrzymać ma gracz po poprawnym przepisaniu kodu
# MONEY — pieniądze, WYMAGANY PLUGIN VAULT i inny plugin dodający ekonomię na serwerze
# ITEM — itemy
awardType: ITEM

# ilość pieniędzy, jaką ma otrzymać gracz po poprawnym przepisaniu kodu
awardMoney: 300

# w jakich sekundach przed końcem ma zostać wyświetlone przypomnienie o kodzie
# wpisz 0, jeśli takowego przypomnienia ma nie być
codeNotifySeconds: [5, 10]

# itemy, które ma otrzymać gracz po poprawnym przepisaniu kodu
giveItem:
  1:
    material: DIAMOND_BLOCK
    amount: 64
    name: "&b&lBloki diamentu za poprawne przepisanie kodu"